import { type Listing } from "@/types";

export const MOCK_LISTINGS: Listing[] = [
  { id: '1', farmerId: 'f1', farmerName: 'Emeka Farms', cropType: 'Tomato', quantity: 50, pricePerKg: 800, location: 'Kano', state: 'Kano', harvestTime: new Date(Date.now() - 3_600_000 * 5).toISOString(), currentFreshness: 90, imageUrl: '', status: 'AVAILABLE', createdAt: new Date().toISOString() },
  { id: '2', farmerId: 'f2', farmerName: 'Bello Agro', cropType: 'Yam', quantity: 200, pricePerKg: 350, location: 'Plateau', state: 'Plateau', harvestTime: new Date(Date.now() - 3_600_000 * 18).toISOString(), currentFreshness: 64, imageUrl: '', status: 'AVAILABLE', createdAt: new Date().toISOString() },
  { id: '3', farmerId: 'f3', farmerName: 'Ada Fresh', cropType: 'Pepper', quantity: 30, pricePerKg: 1200, location: 'Enugu', state: 'Enugu', harvestTime: new Date(Date.now() - 3_600_000 * 40).toISOString(), currentFreshness: 30, imageUrl: '', status: 'AVAILABLE', createdAt: new Date().toISOString() },
  { id: '4', farmerId: 'f4', farmerName: 'Tunde Harvest', cropType: 'Maize', quantity: 500, pricePerKg: 180, location: 'Oyo', state: 'Oyo', harvestTime: new Date(Date.now() - 3_600_000 * 2).toISOString(), currentFreshness: 96, imageUrl: '', status: 'AVAILABLE', createdAt: new Date().toISOString() },
  { id: '5', farmerId: 'f5', farmerName: 'Ngozi Greens', cropType: 'Cabbage', quantity: 80, pricePerKg: 400, location: 'Anambra', state: 'Anambra', harvestTime: new Date(Date.now() - 3_600_000 * 12).toISOString(), currentFreshness: 76, imageUrl: '', status: 'AVAILABLE', createdAt: new Date().toISOString() },
  { id: '6', farmerId: 'f6', farmerName: 'Kola Roots', cropType: 'Cassava', quantity: 300, pricePerKg: 120, location: 'Lagos', state: 'Lagos', harvestTime: new Date(Date.now() - 3_600_000 * 8).toISOString(), currentFreshness: 84, imageUrl: '', status: 'AVAILABLE', createdAt: new Date().toISOString() },
];