import { CropType, Listing, Order } from "@/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    cropType: "Tomato",
    quantity: 50,
    pricePerKg: 800,
    location: "Kano",
    state: "Kano",
    harvestTime: new Date(Date.now() - 3_600_000 * 5).toISOString(),
    currentFreshness: 90,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    cropType: "Pepper",
    quantity: 30,
    pricePerKg: 1200,
    location: "Kano",
    state: "Kano",
    harvestTime: new Date(Date.now() - 3_600_000 * 38).toISOString(),
    currentFreshness: 34,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    cropType: "Maize",
    quantity: 200,
    pricePerKg: 180,
    location: "Kano",
    state: "Kano",
    harvestTime: new Date(Date.now() - 3_600_000 * 2).toISOString(),
    currentFreshness: 96,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-010",
    buyerId: "b1",
    buyerName: "Chukwuemeka Obi",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    listingId: "1",
    cropType: "Tomato",
    quantity: 20,
    totalAmount: 16000,
    status: "PAYMENT_HELD",
    pickupAddress: "Kano Farm Hub",
    deliveryAddress: "14 Marina St, Lagos",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ORD-011",
    buyerId: "b2",
    buyerName: "Fatima Aliyu",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    listingId: "2",
    cropType: "Pepper",
    quantity: 10,
    totalAmount: 12000,
    status: "IN_TRANSIT",
    pickupAddress: "Kano Farm Hub",
    deliveryAddress: "Abuja FCT",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CROP_EMOJI: Record<string, string> = {
  Tomato: "🍅",
  Yam: "🥔",
  Cassava: "🌿",
  Maize: "🌽",
  Rice: "🍚",
  Pepper: "🌶️",
  Onion: "🧅",
  Plantain: "🍌",
  Carrot: "🥕",
  Cabbage: "🥬",
};

export const CROP_TYPES: { value: CropType; emoji: string }[] = [
  { value: "Tomato", emoji: "🍅" },
  { value: "Yam", emoji: "🥔" },
  { value: "Cassava", emoji: "🌿" },
  { value: "Maize", emoji: "🌽" },
  { value: "Rice", emoji: "🍚" },
  { value: "Pepper", emoji: "🌶️" },
  { value: "Onion", emoji: "🧅" },
  { value: "Plantain", emoji: "🍌" },
  { value: "Carrot", emoji: "🥕" },
  { value: "Cabbage", emoji: "🥬" },
];
