import { DisputeCase } from "@/types";

export const MOCK_DISPUTES: DisputeCase[] = [
  {
    id: "DIS-001",
    orderId: "ORD-005",
    buyerName: "Chukwuemeka Obi",
    farmerName: "Ngozi Greens",
    cropType: "Cabbage",
    amount: 12000,
    reason: "Produce arrived spoiled or rotten",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: "OPEN",
  },
  {
    id: "DIS-002",
    orderId: "ORD-008",
    buyerName: "Fatima Aliyu",
    farmerName: "Kola Roots",
    cropType: "Cassava",
    amount: 8400,
    reason: "Quantity was less than ordered",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: "OPEN",
  },
];

export const MOCK_PAYMENTS = [
  {
    id: "PAY-091",
    orderId: "ORD-001",
    buyer: "Chukwuemeka Obi",
    farmer: "Emeka Farms",
    crop: "Tomato",
    amt: 16000,
    status: "HELD",
    date: "Mar 22, 2026",
  },
  {
    id: "PAY-090",
    orderId: "ORD-002",
    buyer: "Chukwuemeka Obi",
    farmer: "Bello Agro",
    crop: "Yam",
    amt: 17500,
    status: "HELD",
    date: "Mar 23, 2026",
  },
  {
    id: "PAY-089",
    orderId: "ORD-003",
    buyer: "Chukwuemeka Obi",
    farmer: "Ada Fresh",
    crop: "Pepper",
    amt: 12000,
    status: "RELEASED",
    date: "Mar 18, 2026",
  },
  {
    id: "PAY-088",
    orderId: "ORD-005",
    buyer: "Chukwuemeka Obi",
    farmer: "Ngozi Greens",
    crop: "Cabbage",
    amt: 12000,
    status: "DISPUTED",
    date: "Mar 17, 2026",
  },
  {
    id: "PAY-087",
    orderId: "ORD-010",
    buyer: "Musa Garba",
    farmer: "Emeka Farms",
    crop: "Tomato",
    amt: 40000,
    status: "HELD",
    date: "Mar 24, 2026",
  },
  {
    id: "PAY-086",
    orderId: "ORD-011",
    buyer: "Ngozi Okonkwo",
    farmer: "Bello Agro",
    crop: "Yam",
    amt: 70000,
    status: "HELD",
    date: "Mar 23, 2026",
  },
  {
    id: "PAY-085",
    orderId: "ORD-009",
    buyer: "Tunde Bello",
    farmer: "Emeka Farms",
    crop: "Maize",
    amt: 14400,
    status: "RELEASED",
    date: "Mar 19, 2026",
  },
  {
    id: "PAY-084",
    orderId: "ORD-008",
    buyer: "Fatima Aliyu",
    farmer: "Kola Roots",
    crop: "Cassava",
    amt: 8400,
    status: "DISPUTED",
    date: "Mar 16, 2026",
  },
  {
    id: "PAY-083",
    orderId: "ORD-007",
    buyer: "Musa Garba",
    farmer: "Ada Fresh",
    crop: "Pepper",
    amt: 30000,
    status: "RELEASED",
    date: "Mar 14, 2026",
  },
];
