import { Listing, Order } from "@/types";

export const MOCK_LOADS: (Listing & {
  orderId: string;
  pickupAddress: string;
  deliveryAddress: string;
  distance: string;
})[] = [
  {
    id: "1",
    orderId: "ORD-020",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    cropType: "Tomato",
    quantity: 50,
    pricePerKg: 800,
    location: "Kano",
    state: "Kano",
    harvestTime: new Date(Date.now() - 3_600_000 * 5).toISOString(),
    currentFreshness: 90,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
    pickupAddress: "Kano Farm Hub, Kano",
    deliveryAddress: "14 Marina St, Lagos Island",
    distance: "1,114 km",
  },
  {
    id: "2",
    orderId: "ORD-021",
    farmerId: "f2",
    farmerName: "Bello Agro",
    cropType: "Yam",
    quantity: 200,
    pricePerKg: 350,
    location: "Plateau",
    state: "Plateau",
    harvestTime: new Date(Date.now() - 3_600_000 * 18).toISOString(),
    currentFreshness: 64,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
    pickupAddress: "Plateau Market, Jos",
    deliveryAddress: "Garki Market, Abuja FCT",
    distance: "186 km",
  },
  {
    id: "3",
    orderId: "ORD-022",
    farmerId: "f3",
    farmerName: "Ada Fresh",
    cropType: "Pepper",
    quantity: 30,
    pricePerKg: 1200,
    location: "Enugu",
    state: "Enugu",
    harvestTime: new Date(Date.now() - 3_600_000 * 8).toISOString(),
    currentFreshness: 84,
    status: "AVAILABLE",
    createdAt: new Date().toISOString(),
    pickupAddress: "Enugu Farm Collective",
    deliveryAddress: "Mile 12 Market, Lagos",
    distance: "642 km",
  },
];

export const MOCK_ACTIVE: Order[] = [
  {
    id: "ORD-020",
    buyerId: "b4",
    buyerName: "Musa Garba",
    farmerId: "f1",
    farmerName: "Emeka Farms",
    logisticsId: "l1",
    listingId: "1",
    cropType: "Tomato",
    quantity: 50,
    totalAmount: 40000,
    status: "PAYMENT_HELD",
    pickupAddress: "Kano Farm Hub, Kano",
    deliveryAddress: "14 Marina St, Lagos Island",
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ORD-021",
    buyerId: "b5",
    buyerName: "Ngozi Okonkwo",
    farmerId: "f2",
    farmerName: "Bello Agro",
    logisticsId: "l1",
    listingId: "2",
    cropType: "Yam",
    quantity: 200,
    totalAmount: 70000,
    status: "IN_TRANSIT",
    pickupAddress: "Plateau Market, Jos",
    deliveryAddress: "Garki Market, Abuja FCT",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
